name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
            cc: cl.exe
            cxx: cl.exe
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/checkout@v2
        with:
          repository: 'KhronosGroup/OpenXR-SDK'
          path: 'OpenXR-SDK'

      - name: setup VsDev environment
        if: runner.os == 'Windows'
        uses: mondradiko/gha-setup-vsdevenv@v3

      - uses: mondradiko/gha-setup-ninja@v3
      - name: Install OpenXR SDK
        shell: bash
        working-directory: 'OpenXR-SDK'
        run: |
          mkdir build
          pushd build
          cmake -GNinja ..
          cmake --build .
          sudo cmake --install .
          popd

      - name: apt
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install \
            libglvnd-dev libxrandr-dev libwayland-dev \
            libuv1-dev libvulkan-dev glslang-tools libsdl2-dev

      - uses: mondradiko/gha-setup-ninja@v3
      - name: Configure
        run: |
          mkdir build
          pushd build
          cmake -GNinja -DTRACY_ENABLE=ON ..

      - name: compile
        run: ninja -C build
