name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          #- os: windows-latest
          #  cc: cl.exe
          #  cxx: cl.exe
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    steps:
      - name: apt
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install \
            ninja-build \
            libglvnd-dev libxrandr-dev libwayland-dev \
            libuv1-dev libvulkan-dev glslang-tools libsdl2-dev

      - uses: actions/checkout@v2
        with:
          repository: 'KhronosGroup/OpenXR-SDK'
          path: 'OpenXR-SDK'

      - name: Configure OpenXR SDK (Linux)
        working-directory: 'OpenXR-SDK'
        run: |
          mkdir build
          pushd build
          cmake -DPRESENTATION_BACKEND=xlib -DOpenGL_GL_PREFERENCE=GLVND -GNinja ..

      - name: Build and Install OpenXR SDK
        working-directory: 'OpenXR-SDK/build'
        run: |
          cmake --build .
          sudo cmake --install .
          popd

      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: setup VsDev environment
        if: runner.os == 'Windows'
        uses: mondradiko/gha-setup-vsdevenv@v3

      - name: configure
        run: |
          mkdir build
          cd build
          cmake -GNinja -DTRACY_ENABLE=ON ..

      - name: compile
        run: ninja -C build
